name: CAFÉ ANCESTRAL
favicon: null
layout_spectrum: 0.2835556853096932
typography_spectrum: 0.7452516122721136
title: Living in harmony with nature
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.7418281394056976
  lightness: 0.24286607140675187
  saturation: 0.9498186965938658
  rhythmicContrast: 0.2103897645138204
purpose: []
