name: CAFÉ ANCESTRAL
favicon: null
layout_spectrum: 0.7672066423110664
typography_spectrum: 0.7649488125462085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.04959329986013472
  lightness: 0.33734636823646724
  saturation: 0.27744425903074443
  rhythmicContrast: 0.2513199665118009
purpose: []
